/*
 * rpdf.h – C API for template-driven HTML → PDF generation.
 *          Auto-generated by cbindgen from src/ffi.rs.
 *          Do not edit manually; changes will be overwritten on next build.
 *
 * MEMORY MANAGEMENT
 *   - Byte buffers (*out_buf) returned by rpdf_* functions MUST be freed
 *     by calling rpdf_free_buffer(*out_buf, *out_len).
 *   - String pointers (*out_json) MUST be freed with rpdf_free_string().
 *   - rpdf_last_error() returns a pointer valid until the next call on this
 *     thread – do NOT free it.
 *
 * ERROR CODES
 *   0  success
 *   1  null pointer argument
 *   2  invalid UTF-8 in input
 *   3  pipeline / layout error
 *   4  render / PDF error
 *
 * LINK FLAGS
 *   Windows MSVC  : pdf_forge.lib  Ws2_32.lib Bcrypt.lib Ntdll.lib Userenv.lib
 *   Windows MinGW : -lpdf_forge -lws2_32 -lbcrypt -lntdll -luserenv
 *   Linux/macOS   : -lpdf_forge -lpthread -ldl -lm
 */

#ifndef RPDF_H
#define RPDF_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Default page margins in points.
 */
#define PAGE_MARGIN_PT 40.0

/**
 * Page orientation for use in [`RpdfPipelineConfig`].
 */
typedef enum RpdfPageOrientation {
  /**
   * Portrait mode: height > width (default).
   */
  Portrait = 0,
  /**
   * Landscape mode: width > height.
   */
  Landscape = 1,
} RpdfPageOrientation;

/**
 * Optional configuration for PDF generation passed to the `*_ex` functions.
 *
 * Fields set to `0` (or `NULL` for `title`) fall back to their A4 defaults:
 * - `page_width`  → 595.28 pt
 * - `page_height` → 841.89 pt
 * - `page_margin` → 40 pt
 * - `title`       → "rpdf output"
 */
typedef struct RpdfPipelineConfig {
  /**
   * Null-terminated UTF-8 document title embedded in PDF metadata.
   * Pass `NULL` to use the default title ("rpdf output").
   */
  const char *title;
  /**
   * Page width in points. Pass `0.0` to use the default (A4 = 595.28).
   */
  float page_width;
  /**
   * Page height in points. Pass `0.0` to use the default (A4 = 841.89).
   */
  float page_height;
  /**
   * Page margin in points. Pass `0.0` to use the default (40 pt).
   */
  float page_margin;
  /**
   * Page orientation (portrait = 0, landscape = 1).
   */
  enum RpdfPageOrientation orientation;
} RpdfPipelineConfig;







/**
 * Generate a PDF from an HTML template string.
 *
 * # Parameters
 * - `html_ptr`: pointer to UTF-8 HTML bytes (not necessarily null-terminated)
 * - `html_len`: length of the HTML data in bytes
 * - `out_buf`: on success, receives a pointer to heap-allocated PDF bytes
 * - `out_len`: on success, receives the length of the PDF buffer
 *
 * # Returns
 * `0` on success, non-zero on error. On error, call `rpdf_last_error`.
 *
 * # Safety
 * - `html_ptr` must point to `html_len` valid bytes.
 * - `out_buf` and `out_len` must be valid pointers.
 * - The caller must free `*out_buf` by calling `rpdf_free_buffer`.
 */
int rpdf_generate_pdf(const uint8_t *html_ptr,
                      uint32_t html_len,
                      uint8_t **out_buf,
                      uint32_t *out_len);

/**
 * Generate a PDF and also return the layout config JSON.
 *
 * # Parameters
 * - `html_ptr`, `html_len`: the HTML input
 * - `out_pdf_buf`, `out_pdf_len`: PDF output
 * - `out_json_ptr`: receives a pointer to a null-terminated JSON string
 *
 * # Returns
 * `0` on success.
 *
 * # Safety
 * Same as `rpdf_generate_pdf`. Additionally, `*out_json_ptr` must be freed
 * with `rpdf_free_string`.
 */
int rpdf_generate_pdf_with_layout(const uint8_t *html_ptr,
                                  uint32_t html_len,
                                  uint8_t **out_pdf_buf,
                                  uint32_t *out_pdf_len,
                                  char **out_json_ptr);

/**
 * Compute only the layout config (no PDF rendering). Returns JSON.
 *
 * # Parameters
 * - `html_ptr`, `html_len`: the HTML input
 * - `out_json_ptr`: receives a pointer to a null-terminated JSON string
 *
 * # Returns
 * `0` on success.
 */
int rpdf_compute_layout(const uint8_t *html_ptr, uint32_t html_len, char **out_json_ptr);

/**
 * Generate a PDF from HTML with a custom [`RpdfPipelineConfig`].
 *
 * # Parameters
 * - `html_ptr`, `html_len`: UTF-8 HTML input
 * - `cfg`: optional pointer to an [`RpdfPipelineConfig`]; pass `NULL` for defaults
 * - `out_buf`, `out_len`: PDF output
 *
 * # Returns
 * `0` on success.
 *
 * # Safety
 * - `html_ptr` must point to `html_len` valid bytes.
 * - `cfg`, if non-null, must be a valid pointer to a fully-initialised
 *   [`RpdfPipelineConfig`] whose `title` field (if non-null) is a valid
 *   null-terminated UTF-8 string.
 * - The caller must free `*out_buf` with `rpdf_free_buffer`.
 */
int rpdf_generate_pdf_ex(const uint8_t *html_ptr,
                         uint32_t html_len,
                         const struct RpdfPipelineConfig *cfg,
                         uint8_t **out_buf,
                         uint32_t *out_len);

/**
 * Generate a PDF and layout JSON from HTML with a custom [`RpdfPipelineConfig`].
 *
 * # Parameters
 * - `html_ptr`, `html_len`: UTF-8 HTML input
 * - `cfg`: optional pointer to an [`RpdfPipelineConfig`]; pass `NULL` for defaults
 * - `out_pdf_buf`, `out_pdf_len`: PDF output (free with `rpdf_free_buffer`)
 * - `out_json_ptr`: layout JSON output (free with `rpdf_free_string`)
 *
 * # Returns
 * `0` on success.
 *
 * # Safety
 * Same as `rpdf_generate_pdf_ex`.
 */
int rpdf_generate_pdf_with_layout_ex(const uint8_t *html_ptr,
                                     uint32_t html_len,
                                     const struct RpdfPipelineConfig *cfg,
                                     uint8_t **out_pdf_buf,
                                     uint32_t *out_pdf_len,
                                     char **out_json_ptr);

/**
 * Compute only the layout config JSON from HTML with a custom [`RpdfPipelineConfig`].
 *
 * # Parameters
 * - `html_ptr`, `html_len`: UTF-8 HTML input
 * - `cfg`: optional pointer to an [`RpdfPipelineConfig`]; pass `NULL` for defaults
 * - `out_json_ptr`: layout JSON output (free with `rpdf_free_string`)
 *
 * # Returns
 * `0` on success.
 *
 * # Safety
 * Same as `rpdf_generate_pdf_ex`.
 */
int rpdf_compute_layout_ex(const uint8_t *html_ptr,
                           uint32_t html_len,
                           const struct RpdfPipelineConfig *cfg,
                           char **out_json_ptr);

/**
 * Render a PDF from a layout config JSON string.
 *
 * This allows pre-computing the layout and rendering separately.
 */
int rpdf_render_from_layout(const char *json_ptr, uint8_t **out_buf, uint32_t *out_len);

/**
 * Free a PDF buffer returned by `rpdf_generate_pdf`.
 *
 * # Safety
 * `buf` must have been returned by a previous `rpdf_generate_pdf` (or similar)
 * call, and `len` must be the corresponding length.
 */
void rpdf_free_buffer(uint8_t *buf, uint32_t len);

/**
 * Free a string returned by `rpdf_last_error` or layout config JSON.
 *
 * # Safety
 * `s` must have been returned by Rust's `CString::into_raw`.
 */
void rpdf_free_string(char *s);

/**
 * Retrieve the last error message. Returns a null-terminated string.
 *
 * The returned pointer is valid until the next `rpdf_*` call on the same
 * thread. The caller should **not** free this pointer – it is managed
 * internally.
 *
 * Returns null if no error has occurred.
 */
const char *rpdf_last_error(void);

/**
 * Return the library version as a null-terminated string.
 * The caller must **not** free this pointer.
 */
const char *rpdf_version(void);

#endif  /* RPDF_H */
